server:
  port: 9091
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:team
    username: system
    password: Daniela2024
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: none